### ISSUE TITLE
Search movies containing spaces and with category

### ISSUE THREAD

**Issue by SanketBaraiya** [nishantshah977/torrent-api#1]
How to search movies containing spaces and also how to search in particular category. Thanks

**Comment by nishantshah977** [comment]
You can search movies name containing spaces. But for better results you and trying adding `_` `-` or `.` 

Currently there's no method to search in particular category. You can send a PR. I'll review it and merge it.

**P.S:** I'm likely to add this feature in upcoming days. I'm busy with my schedules.
